name: TEMP test secrets inherit (delete after debugging)

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/check-fog-version.yml
    with:
      branch: "dev-branch"
    secrets: inherit
