name: GitHub Workflow Immortality

on:
  workflow_dispatch:
  schedule:
    # run once a month on the first day of the month at 00:20 UTC
    - cron: '20 0 1 * *'

jobs:
  keepalive:
    name: Fog Release Workflow Immortality

    runs-on: ubuntu-latest
    permissions: {}

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.FOG_WORKFLOWS_APPID }}
          private-key: ${{ secrets.FOG_WORKFLOWS_PRIVATE_KEY }}
          owner: FOGProject
          
      - name: Keep cronjob based triggers of GitHub workflows alive
        uses: PhrozenByte/gh-workflow-immortality@v1
        with:
          secret: ${{ steps.app-token.outputs.token }}
          repos: FOGProject/fog-workflows
